# version: 0.2

# phases:
#   pre_build:
#     commands:
#       - echo Logging in to Amazon ECR...
#       - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 851725476048.dkr.ecr.ap-south-1.amazonaws.com

#   build:
#     commands:
#       - echo Building the Docker image using docker-compose...
#       - cd backend
#       - docker-compose build backend
#       - echo Tagging the Docker image...
#       - docker tag my-backend:latest 851725476048.dkr.ecr.ap-south-1.amazonaws.com/my-backend:latest

#   post_build:
#     commands:
#       - echo Pushing the Docker image to Amazon ECR...
#       - docker push 851725476048.dkr.ecr.ap-south-1.amazonaws.com/my-backend:latest
#       - echo Build complete.

# artifacts:
#   files: []

version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 537124946002.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image using docker-compose...
      - cd backend
      - docker-compose build backend
      - echo Tagging the Docker image...
      - docker tag my-backend:latest 537124946002.dkr.ecr.ap-south-1.amazonaws.com/my-backend:latest

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 537124946002.dkr.ecr.ap-south-1.amazonaws.com/my-backend:latest
      - echo Returning to root directory...
      - cd ..
      - echo Generating imagedefinitions.json at root...
      - printf '[{"name":"clicksolver-backend","imageUri":"537124946002.dkr.ecr.ap-south-1.amazonaws.com/my-backend:latest"}]' > imagedefinitions.json
      - echo Build complete.

artifacts:
  files:
    - imagedefinitions.json
