# version: "3.8"

# services:
#   backend:
#     build: .
#     container_name: my-backend
#     ports:
#       - "5000:5000"
#     environment:
#       - DB_HOST=db
#       - DB_USER=postgres
#       - DB_PASSWORD=Yaswanth@123
#       - DB_PORT=5432
#       - DB_NAME=clicksolver
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     container_name: my-postgres-db
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: Yaswanth@123
#       POSTGRES_DB: clicksolver
#     ports:
#       - "5432:5432"
#     volumes:
#       - pg_data:/var/lib/postgresql/data

# volumes:
#   pg_data:

version: "3.8"

services:
  backend:
    build: .
    image: my-backend:latest
    container_name: my-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=Yaswanth@123
      - DB_PORT=5432
      - DB_NAME=clicksolver
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Yaswanth@123
      POSTGRES_DB: clicksolver
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
